---
- name: Create kafka user and group
  include_role:
    name: users
  vars:
    users:
      - username: kafka
        name: kafka
        home: /opt/kafka
        shell: /usr/sbin/nologin
        is_system_user: true
    groups_to_create:
      - name: kafka

- name: Change /opt/kafka ownership, group and permissions
  file:
    path: /opt/kafka
    owner: kafka
    group: kafka
    mode: '0755'
    state: directory
    recurse: yes

- name: Change /wsp_var/log/kafka ownership, group and permissions
  file:
    path: /wsp_var/log/kafka
    owner: kafka
    group: kafka
    mode: '0744'
    state: directory
    recurse: yes

- name: write cluster identifiers to a helper file
  template:
    src: kafka-meta.helper.txt.j2
    dest: "{{ kafka_config_dir }}/kafka-meta.helper.txt"
    owner: kafka
    group: kafka
    mode: '0740'
  notify: reset kafka data

- name: Flush handlers (reset data if needed)
  meta: flush_handlers

- name: Change data_dir ownership, group and permissions
  file:
    path: "{{ kafka_data_dir }}"
    owner: kafka
    group: kafka
    mode: '0740'
    state: directory
    recurse: yes

- name: Configure logger settings
  template:
    src: log4j.properties.j2
    dest: "{{ kafka_log_config_dir }}log4j.properties"
    owner: kafka
    group: kafka
    mode: '0640'
  notify: restart kafka

- name: Configure kafka settings
  template:
    src: kafka-server.conf.j2
    dest: "{{ kafka_config_dir }}kafka-server.conf"
    owner: kafka
    group: kafka
    mode: '0640'
  notify: restart kafka

- name: enable kafka service
  systemd:
    name: "kafka"
    state: "{{ kafka_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ kafka_enabled }}"
    daemon_reload: yes

- name: reassign partition replication
  import_tasks: reassign_replication.yml
  when: kafka_reassign_replication | bool
